- paged:
    queryParameters:
      start:
        description: The first page to return
        type: number
        example: 1
      pages:
        description: The number of pages to return
        type: number
        example: 3
- accountable:
    headers:
      X-Accounting-Code:
        description: |
          Your accounting code, for tracking 
          usage of this API
        required: true
        example: CLDSTORE-203
